apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: final-scc
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
allowPrivilegeEscalation: true
priority: 50
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
