kind: Deployment
apiVersion: apps/v1
metadata:
  name: libreoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreoffice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: libreoffice
    spec:
      containers:
        - name: libreoffice
          image: 'lscr.io/linuxserver/libreoffice:latest'
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 3001
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      serviceAccountName: libra
      schedulerName: default-scheduler
