apiVersion: ocpztp.kasmmod.office.ocpztp.com/v1
kind: Kasmmod
metadata:
  labels:
    app.kubernetes.io/name: kasmmod
    app.kubernetes.io/instance: kasmmod-sample
    app.kubernetes.io/part-of: kasmmod
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kasmmod
  name: sample1
spec:
  size: 2
  port: 80
  image: docker.io/sainikhil2226/tic-tac-toe:v1
  serviceaccount: sample1
